hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/CircularDoublyLinkedList.o -c ./src/CircularDoublyLinkedList.cpp
	g++ -I ./include/ -o ./lib/Node.o -c ./src/Node.cpp
	g++ -I ./include/ -o ./bin/test ./lib/CircularDoublyLinkedList.o ./lib/Node.o ./src/Main.cpp
	
calistir:
	./bin/test